version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: cred_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: credpal
    ports:
      - "5435:5432" # Changed port to 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
